apiVersion: v1
kind: Pod
metadata:
  name: pod-<change-me-to-your-name>
spec:
  containers:
  - name: mypod
    image: alpine:latest 
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c", "sleep infinity"]
